### ISSUE TITLE
Vim polyglot link wrong

### ISSUE THREAD

**Issue by rohanorton** [ElmCast/.vim#1]
Hey, thanks a lot for this. The vim-polyglot link points to https://github.com/ElmCast/.vim/blob/master/sheerun/vim-polyglot when I think you meant to point it to https://github.com/sheerun/vim-polyglot

**Comment by ajhager** [comment]
Fixed in 788b4110a7ffdf39352f97836fbb3a729817b895. Thanks you for the heads up!
